export const initialData = {
  currentProspects: [
    {
      id: 1,
      projectName: 'The DEVOPS Project',
      location: 'Amsterdam',
      lead: 'Chuck Norris',
      launchDate: 'January 2025',
      rag: 'green',
    },
    {
      id: 2,
      projectName: 'Newsletter',
      location: 'Berlin',
      lead: 'Ron Burgundy',
      launchDate: 'August 2028',
      rag: 'amber',
    },
    {
      id: 3,
      projectName: 'Psycho',
      location: 'London',
      lead: 'Patrick Bateman',
      launchDate: 'December 2025',
      rag: 'green',
    },
    {
      id: 4,
      projectName: 'Bofarull',
      location: 'Barcelona',
      lead: 'Josep Lopes',
      launchDate: 'February 2026',
      rag: 'red',
    },
    {
      id: 5,
      projectName: 'Bogeyman',
      location: 'Viena',
      lead: 'Keyser Söze',
      launchDate: 'August 2027',
      rag: 'amber',
    },
  ],
  currentProjects: [
    {
      id: 6,
      projectName: 'Rose',
      location: 'Praha',
      lead: 'Lester Burnham',
      launchDate: 'January 2029',
      rag: 'green',
    },
    {
      id: 7,
      projectName: 'Appliance',
      location: 'Budapest',
      lead: 'Shaun Riley',
      launchDate: 'March 2028',
      rag: 'red',
    },
    {
      id: 8,
      projectName: 'Postcard',
      location: 'Paris',
      lead: 'Amélie Poulain',
      launchDate: 'September 2025',
      rag: 'green',
    },
    {
      id: 9,
      projectName: 'Quarter Pounder',
      location: 'Ljubljana',
      lead: 'Jules Winnfield',
      launchDate: 'July 2026',
      rag: 'red',
    },
    {
      id: 10,
      projectName: 'T2',
      location: 'Lisboa',
      lead: 'Sarah Connor',
      launchDate: 'December 2025',
      rag: 'amber',
    },
    {
      id: 11,
      projectName: 'Malign',
      location: 'Athens',
      lead: 'Hans Landa',
      launchDate: 'December 2026',
      rag: 'red',
    },
  ],
};
