name: Build DotNet
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: backend/src
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: backend/src
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: backend/src
      - name: Install Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools
        working-directory: backend/src
      - name: Package
        run: dotnet lambda package -c Release -f netcoreapp3.1 --output-package "..\..\artifacts\Ohpen.Executive.Dashboard.WebApi.zip"  
        working-directory: backend/src/Ohpen.Executive.Dashboard.WebApi
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: backend/*.zip
  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1