name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: backend/src
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: backend/src
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: backend/src
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: backend/*.zip
